const BASE_EXTRAS = {
  stats: [
    { label: '누적 고객', value: '12K+', desc: '지금까지 함께한 고객 수' },
    { label: '평균 만족도', value: '4.9/5', desc: '최근 3개월 기준' },
    { label: '프로젝트', value: '320+', desc: '검증된 성공 사례' },
  ],
  steps: [
    { title: '상담 요청', desc: '간단한 정보를 남기면 바로 연락드려요.' },
    { title: '전략 설계', desc: '목표와 대상에 맞춘 플랜을 제안합니다.' },
    { title: '실행 & 개선', desc: '데이터를 기반으로 지속 개선합니다.' },
  ],
  cta: {
    title: '지금 바로 시작해 보세요',
    desc: '무료 상담으로 방향을 잡고 빠르게 실행하세요.',
    primary: '상담 신청',
    secondary: '가이드 보기',
  },
  contact: {
    email: 'hello@example.com',
    phone: '02-1234-5678',
    address: '서울시 강남구 테헤란로 123',
    hours: '월-금 09:00-18:00',
  },
  socials: [
    { label: 'Instagram', url: 'https://instagram.com' },
    { label: 'YouTube', url: 'https://youtube.com' },
    { label: 'Blog', url: 'https://blog.example.com' },
  ],
}

const cloneExtras = () => ({
  stats: BASE_EXTRAS.stats.map((s) => ({ ...s })),
  steps: BASE_EXTRAS.steps.map((s) => ({ ...s })),
  cta: { ...BASE_EXTRAS.cta },
  contact: { ...BASE_EXTRAS.contact },
  socials: BASE_EXTRAS.socials.map((s) => ({ ...s })),
})

const withExtras = (overrides = {}) => {
  const base = cloneExtras()
  return {
    ...base,
    ...overrides,
    cta: { ...base.cta, ...(overrides.cta || {}) },
    contact: { ...base.contact, ...(overrides.contact || {}) },
    socials: overrides.socials ? overrides.socials.map((s) => ({ ...s })) : base.socials,
    stats: overrides.stats ? overrides.stats.map((s) => ({ ...s })) : base.stats,
    steps: overrides.steps ? overrides.steps.map((s) => ({ ...s })) : base.steps,
  }
}

export const TEMPLATE_PRESETS = {
  cafe: {
    id: 'cafe',
    label: '카페',
    keywords: ['카페', '커피', '라떼', '브런치', '디저트', '원두'],
    sections: {
      features: '시그니처',
      gallery: '매장 스냅',
      testimonials: '단골 후기',
      pricing: '세트 메뉴',
      faq: '자주 묻는 질문',
      contact: '문의하기',
      stats: '카페 지표',
      steps: '이용 흐름',
      cta: '지금 예약',
    },
    defaults: withExtras({
      title: '오로라 로스터리',
      slogan: '매일 로스팅하는 향긋한 하루',
      heroCta: '예약하기',
      heroCtaSecondary: '메뉴 보기',
      features: [
        '스페셜티 원두와 매일 로스팅',
        '시즌 디저트와 브런치',
        '아늑한 좌석과 무료 Wi-Fi',
        '테이크아웃 10% 할인',
      ],
      testimonials: [
        { name: '서연', role: '단골', quote: '원두 향이 정말 좋아요. 매일 들르고 싶어요.' },
        { name: '민수', role: '프리랜서', quote: '작업하기 좋은 분위기와 커피 맛 모두 최고.' },
        { name: '지아', role: '브런치 마니아', quote: '디저트가 늘 새롭고 예뻐요.' },
      ],
      pricing: [
        { name: '모닝 세트', price: '₩7,900', desc: '아메리카노 + 크루아상', perks: ['07:00-11:00', '테이크아웃 10%'] },
        { name: '시그니처 세트', price: '₩12,500', desc: '라떼 + 디저트', perks: ['시즌 메뉴 포함', '선물 포장'] },
        { name: '브런치 세트', price: '₩15,900', desc: '브런치 + 음료', perks: ['주말 한정', '예약 우선'] },
      ],
      faq: [
        { q: '주차가 가능한가요?', a: '근처 공용 주차장을 이용하실 수 있습니다.' },
        { q: '반려동물 동반이 가능한가요?', a: '야외 좌석은 가능합니다.' },
        { q: '단체 예약은 어떻게 하나요?', a: '전화 또는 문의 폼으로 연락 주세요.' },
      ],
      galleryEmojis: ['☕️', '🥐', '🍰', '🫘', '🫖', '🍪'],
      stats: [
        { label: '재방문율', value: '78%', desc: '단골 고객 기준' },
        { label: '스페셜 원두', value: '24종', desc: '시즌 별 로테이션' },
        { label: '평균 평점', value: '4.9/5', desc: '리뷰 기준' },
      ],
      steps: [
        { title: '좌석 선택', desc: '원하는 자리와 시간을 선택해요.' },
        { title: '메뉴 예약', desc: '사전 주문으로 기다림 없이 픽업.' },
        { title: '즐기기', desc: '따뜻한 공간에서 여유를 즐겨요.' },
      ],
      cta: {
        title: '오늘의 커피를 예약하세요',
        desc: '지금 예약하면 시그니처 디저트를 할인해 드려요.',
        primary: '예약하기',
        secondary: '메뉴 보기',
      },
    }),
  },
  portfolio: {
    id: 'portfolio',
    label: '포트폴리오',
    keywords: ['포트폴리오', '디자이너', '개발자', '작업', '프로젝트', '이력'],
    sections: {
      features: '주요 역량',
      gallery: '대표 작업',
      testimonials: '클라이언트 후기',
      pricing: '서비스 패키지',
      faq: '협업 안내',
      contact: '문의하기',
      stats: '성과',
      steps: '프로세스',
      cta: '프로젝트 시작',
    },
    defaults: withExtras({
      title: '이하늘 포트폴리오',
      slogan: '브랜드 경험을 디자인하는 프로덕트 디자이너',
      heroCta: '프로젝트 보기',
      heroCtaSecondary: '문의하기',
      features: [
        '리서치부터 프로덕트 런칭까지',
        '디자인 시스템 구축',
        '사용자 중심 문제 해결',
        '스타트업 협업 경험',
      ],
      testimonials: [
        { name: 'J. Kim', role: '프로덕트 리드', quote: '문제를 빠르게 구조화하고 실행하는 능력이 탁월합니다.' },
        { name: 'S. Park', role: '창업자', quote: '짧은 시간에 MVP 품질을 크게 올렸어요.' },
        { name: 'Y. Lee', role: '개발팀', quote: '협업이 매끄럽고 피드백이 명확합니다.' },
      ],
      pricing: [
        { name: '리뷰 세션', price: '₩120,000', desc: '1시간 포트폴리오 리뷰', perks: ['피드백 요약', '개선 방향 제안'] },
        { name: '디자인 스프린트', price: '₩980,000', desc: '3일 집중 개선', perks: ['가설 수립', '프로토타입'] },
        { name: '프로덕트 지원', price: '₩2,400,000', desc: '4주 파트너십', perks: ['주간 리뷰', '우선 대응'] },
      ],
      faq: [
        { q: '협업 기간은 어떻게 되나요?', a: '프로젝트 범위에 따라 2주~3개월입니다.' },
        { q: '원격 협업이 가능한가요?', a: '네, 원격 협업을 기본으로 합니다.' },
        { q: '견적은 어떻게 산정되나요?', a: '일정과 범위를 기준으로 산정합니다.' },
      ],
      galleryEmojis: ['🧩', '📐', '🧠', '🖥️', '📱', '✨'],
      stats: [
        { label: '프로젝트', value: '48+', desc: '다양한 산업 경험' },
        { label: 'NPS', value: '92', desc: '클라이언트 만족도' },
        { label: '런칭', value: '18개', desc: '제품 출시' },
      ],
      steps: [
        { title: '브리프', desc: '목표와 일정 공유' },
        { title: '디자인', desc: '와이어프레임부터 UI까지' },
        { title: '핸드오프', desc: '개발팀과 협업' },
      ],
      cta: {
        title: '포트폴리오 협업 제안',
        desc: '현재 가능한 일정과 범위를 확인하세요.',
        primary: '프로젝트 문의',
        secondary: '포트폴리오 다운로드',
      },
    }),
  },
  shop: {
    id: 'shop',
    label: '쇼핑몰',
    keywords: ['쇼핑몰', '스토어', '상품', '구매', '배송', '리뷰'],
    sections: {
      features: '스토어 특징',
      gallery: '베스트 상품',
      testimonials: '리뷰',
      pricing: '추천 상품',
      faq: '배송/교환',
      contact: '고객센터',
      stats: '스토어 지표',
      steps: '구매 흐름',
      cta: '지금 구매',
    },
    defaults: withExtras({
      title: '라이트 마켓',
      slogan: '필요한 것만 빠르고 믿을 수 있게',
      heroCta: '베스트 상품',
      heroCtaSecondary: '할인 보기',
      features: [
        '오늘 주문, 내일 도착',
        '간편 교환·환불',
        '안전 결제 시스템',
        '리뷰 적립금 지급',
      ],
      testimonials: [
        { name: '유진', role: '구매자', quote: '배송이 정말 빨라서 만족했어요.' },
        { name: '태훈', role: '구매자', quote: '품질 대비 가격이 좋아요.' },
        { name: '소라', role: '구매자', quote: '문의 답변이 친절하고 빠릅니다.' },
      ],
      pricing: [
        { name: '데일리 키트', price: '₩24,900', desc: '필수 아이템 묶음', perks: ['무료 배송', '리뷰 2배'] },
        { name: '프리미엄 패키지', price: '₩49,000', desc: '베스트 셀러 모음', perks: ['선물 포장', '당일 출고'] },
        { name: '시즌 한정', price: '₩19,800', desc: '한정 수량 특가', perks: ['쿠폰 적용', '재고 소진'] },
      ],
      faq: [
        { q: '배송 기간은 얼마나 걸리나요?', a: '평일 기준 1~2일 내 배송됩니다.' },
        { q: '교환/환불 규정은?', a: '수령 후 7일 이내 가능합니다.' },
        { q: '할인 쿠폰은 어떻게 받나요?', a: '회원 가입 시 자동 지급됩니다.' },
      ],
      galleryEmojis: ['🛍️', '📦', '🎁', '💳', '✨', '🧴'],
      stats: [
        { label: '평균 배송', value: '1.6일', desc: '전국 기준' },
        { label: '재구매율', value: '62%', desc: '3개월 기준' },
        { label: '누적 리뷰', value: '8,200+', desc: '실사용 후기' },
      ],
      steps: [
        { title: '상품 선택', desc: '카테고리에서 상품을 골라요.' },
        { title: '결제', desc: '원클릭 안전 결제 지원' },
        { title: '빠른 배송', desc: '바로 출고로 빠르게 도착' },
      ],
      cta: {
        title: '지금 구매하면 무료 배송',
        desc: '회원 전용 쿠폰을 바로 받아보세요.',
        primary: '쿠폰 받기',
        secondary: '베스트 보기',
      },
    }),
  },
  blog: {
    id: 'blog',
    label: '블로그',
    keywords: ['블로그', '글', '기록', '뉴스레터', '콘텐츠', '칼럼'],
    sections: {
      features: '핵심 주제',
      gallery: '최근 포스트',
      testimonials: '구독자 후기',
      pricing: '멤버십',
      faq: '자주 묻는 질문',
      contact: '구독 문의',
      stats: '채널 지표',
      steps: '구독 흐름',
      cta: '구독하기',
    },
    defaults: withExtras({
      title: '느린 기록',
      slogan: '작은 실험과 배움을 기록합니다',
      heroCta: '구독하기',
      heroCtaSecondary: '최근 글',
      features: [
        '매주 올라오는 인사이트',
        '카테고리별 큐레이션',
        '읽기 쉬운 요약',
        '무료 뉴스레터',
      ],
      testimonials: [
        { name: '현아', role: '구독자', quote: '짧은 글이라도 늘 도움이 됩니다.' },
        { name: '도윤', role: '구독자', quote: '정리된 정보 덕분에 시간을 절약했어요.' },
        { name: '라온', role: '구독자', quote: '글 톤이 편안해서 자주 찾아옵니다.' },
      ],
      pricing: [
        { name: 'Free', price: '₩0', desc: '주간 뉴스레터', perks: ['주 1회 발송', '핵심 요약'] },
        { name: 'Plus', price: '₩5,900', desc: '심화 콘텐츠', perks: ['심화 글', '자료 링크'] },
        { name: 'Pro', price: '₩12,000', desc: '전체 아카이브', perks: ['아카이브', 'Q&A 참여'] },
      ],
      faq: [
        { q: '글 업로드 주기는 어떻게 되나요?', a: '주 2~3회 업로드합니다.' },
        { q: '협업 콘텐츠도 가능한가요?', a: '네, 제안 폼으로 연락 주세요.' },
        { q: '멤버십 해지는 언제든 되나요?', a: '언제든 해지 가능합니다.' },
      ],
      galleryEmojis: ['📝', '📚', '🧠', '☕️', '🗂️', '✨'],
      stats: [
        { label: '구독자', value: '5,400+', desc: '월간 활성 구독자' },
        { label: '오픈율', value: '48%', desc: '뉴스레터 평균' },
        { label: '콘텐츠', value: '320편', desc: '누적 발행' },
      ],
      steps: [
        { title: '이메일 등록', desc: '간단하게 구독 신청' },
        { title: '맞춤 큐레이션', desc: '관심사에 맞는 콘텐츠' },
        { title: '매주 수신', desc: '정기적으로 업데이트' },
      ],
      cta: {
        title: '이번 주 콘텐츠를 받아보세요',
        desc: '무료 구독으로 가장 빠르게 소식을 받아요.',
        primary: '무료 구독',
        secondary: '이전 글 보기',
      },
    }),
  },
  company: {
    id: 'company',
    label: '회사',
    keywords: ['회사', '기업', '서비스', '비즈니스', '솔루션', '팀'],
    sections: {
      features: '핵심 가치',
      gallery: '제품 스냅',
      testimonials: '고객 사례',
      pricing: '플랜',
      faq: 'FAQ',
      contact: '문의하기',
      stats: '성과',
      steps: '도입 프로세스',
      cta: '데모 요청',
    },
    defaults: withExtras({
      title: '노바 솔루션',
      slogan: '업무를 단순하게 만드는 클라우드',
      heroCta: '데모 요청',
      heroCtaSecondary: '자료 받기',
      features: [
        '강력한 보안과 백업',
        '빠른 도입과 온보딩',
        '데이터 기반 대시보드',
        '전담 고객 지원',
      ],
      testimonials: [
        { name: '인사이트 팀', role: '마케팅', quote: '운영 시간이 절반으로 줄었어요.' },
        { name: '그로우 컴퍼니', role: 'HR', quote: '교육 비용이 크게 절감되었습니다.' },
        { name: '비전 스튜디오', role: '리드', quote: '대시보드가 정말 직관적입니다.' },
      ],
      pricing: [
        { name: 'Starter', price: '₩49,000', desc: '소규모 팀', perks: ['기본 기능', '이메일 지원'] },
        { name: 'Pro', price: '₩149,000', desc: '성장 팀', perks: ['고급 기능', '우선 지원'] },
        { name: 'Enterprise', price: '문의', desc: '맞춤형', perks: ['전담 매니저', 'SLA'] },
      ],
      faq: [
        { q: '도입까지 얼마나 걸리나요?', a: '평균 1~2주 내 설정 가능합니다.' },
        { q: '데이터 이전 지원이 되나요?', a: '전담 팀이 이전을 도와드립니다.' },
        { q: '계약 조건은 어떻게 되나요?', a: '월/연 단위 계약이 가능합니다.' },
      ],
      galleryEmojis: ['📊', '🧩', '⚙️', '🔒', '📈', '☁️'],
      stats: [
        { label: '도입 기업', value: '120+', desc: '국내외 고객사' },
        { label: '업타임', value: '99.9%', desc: '안정적인 서비스' },
        { label: '지원 속도', value: '24h', desc: '평균 대응 시간' },
      ],
      steps: [
        { title: '진단', desc: '요구 사항과 현황 분석' },
        { title: '설계', desc: '맞춤형 솔루션 제안' },
        { title: '운영', desc: '성과 측정과 개선' },
      ],
      cta: {
        title: '무료 데모를 신청해 보세요',
        desc: '우리 팀이 바로 안내해 드립니다.',
        primary: '데모 신청',
        secondary: '제품 소개서',
      },
    }),
  },
  restaurant: {
    id: 'restaurant',
    label: '레스토랑',
    keywords: ['레스토랑', '맛집', '식당', '예약', '셰프', '코스'],
    sections: {
      features: '대표 메뉴',
      gallery: '공간',
      testimonials: '방문 후기',
      pricing: '코스',
      faq: '안내',
      contact: '예약 문의',
      stats: '레스토랑 지표',
      steps: '예약 흐름',
      cta: '예약하기',
    },
    defaults: withExtras({
      title: '라운지 비스트로',
      slogan: '제철 재료로 만든 오늘의 메뉴',
      heroCta: '예약하기',
      heroCtaSecondary: '메뉴 보기',
      features: [
        '셰프의 시즌 코스',
        '와인 페어링',
        '프라이빗 룸 예약',
        '단체 행사 문의',
      ],
      testimonials: [
        { name: '지수', role: '방문객', quote: '코스 구성이 정말 만족스러웠어요.' },
        { name: '성현', role: '방문객', quote: '분위기와 서비스가 훌륭합니다.' },
        { name: '해린', role: '방문객', quote: '재료의 신선함이 느껴졌어요.' },
      ],
      pricing: [
        { name: '런치 코스', price: '₩28,000', desc: '가볍고 풍성한 구성', perks: ['평일 한정', '예약 권장'] },
        { name: '디너 코스', price: '₩55,000', desc: '시그니처 요리 포함', perks: ['셰프 추천', '와인 할인'] },
        { name: '프라이빗 코스', price: '₩95,000', desc: '맞춤형 코스', perks: ['전용 룸', '기념일 옵션'] },
      ],
      faq: [
        { q: '채식 메뉴가 있나요?', a: '요청 시 맞춤으로 제공됩니다.' },
        { q: '주차가 가능한가요?', a: '근처 주차장을 이용하실 수 있습니다.' },
        { q: '예약 변경은 어떻게 하나요?', a: '방문 하루 전까지 변경 가능합니다.' },
      ],
      galleryEmojis: ['🍽️', '🥂', '🍷', '🪔', '🍝', '🥗'],
      stats: [
        { label: '예약 만족도', value: '4.8/5', desc: '후기 기준' },
        { label: '코스 구성', value: '12종', desc: '계절별 변경' },
        { label: '프라이빗 룸', value: '6개', desc: '행사 이용 가능' },
      ],
      steps: [
        { title: '예약 신청', desc: '원하는 날짜 선택' },
        { title: '확정 안내', desc: '최종 안내 메시지' },
        { title: '방문', desc: '여유롭게 즐기기' },
      ],
      cta: {
        title: '특별한 저녁을 예약하세요',
        desc: '기념일 예약 시 스파클링 제공',
        primary: '예약 문의',
        secondary: '코스 보기',
      },
    }),
  },
  fitness: {
    id: 'fitness',
    label: '피트니스',
    keywords: ['피트니스', '헬스', 'PT', '트레이너', '운동', '체형'],
    sections: {
      features: '프로그램',
      gallery: '시설',
      testimonials: '회원 후기',
      pricing: '이용권',
      faq: '안내',
      contact: '상담 문의',
      stats: '성과 지표',
      steps: '코칭 흐름',
      cta: '무료 체험',
    },
    defaults: withExtras({
      title: '피크 피트니스',
      slogan: '당신에게 맞는 맞춤 코칭',
      heroCta: '상담 신청',
      heroCtaSecondary: '프로그램 보기',
      features: [
        '1:1 맞춤 트레이닝',
        '체형 분석과 자세 교정',
        '식단 코칭 제공',
        '그룹 클래스 운영',
      ],
      testimonials: [
        { name: '예진', role: '회원', quote: '4주 만에 체형이 눈에 띄게 변했어요.' },
        { name: '준서', role: '회원', quote: '코칭이 체계적이라 꾸준히 할 수 있었습니다.' },
        { name: '한별', role: '회원', quote: '시설이 깨끗하고 트레이너가 친절해요.' },
      ],
      pricing: [
        { name: '베이직', price: '₩79,000', desc: '헬스 1개월', perks: ['자유 이용', '기본 상담'] },
        { name: '프리미엄', price: '₩180,000', desc: '헬스 + 그룹', perks: ['그룹 클래스', '체형 측정'] },
        { name: 'PT 집중', price: '₩420,000', desc: 'PT 10회', perks: ['개인 코칭', '식단 가이드'] },
      ],
      faq: [
        { q: '체험이 가능한가요?', a: '1회 무료 체험 가능합니다.' },
        { q: '샤워실이 있나요?', a: '남녀 샤워실을 별도 운영합니다.' },
        { q: 'PT 예약은 어떻게 하나요?', a: '앱 또는 카운터에서 예약 가능합니다.' },
      ],
      galleryEmojis: ['🏋️', '💪', '🧘', '🥊', '🚴', '⏱️'],
      stats: [
        { label: '회원수', value: '1,200+', desc: '활동 회원 기준' },
        { label: '성공률', value: '86%', desc: '목표 달성율' },
        { label: '트레이너', value: '18명', desc: '전문 코치진' },
      ],
      steps: [
        { title: '체형 체크', desc: '개인 목표와 상태 분석' },
        { title: '맞춤 플랜', desc: '운동 & 식단 설계' },
        { title: '루틴 관리', desc: '성과 측정과 개선' },
      ],
      cta: {
        title: '지금 무료 체험을 신청하세요',
        desc: '첫 방문 체험을 무료로 제공합니다.',
        primary: '무료 체험',
        secondary: '트레이너 소개',
      },
    }),
  },
  wedding: {
    id: 'wedding',
    label: '웨딩',
    keywords: ['웨딩', '결혼', '청첩장', '예식', '축하'],
    sections: {
      features: '예식 정보',
      gallery: '갤러리',
      testimonials: '축하 메시지',
      pricing: '일정',
      faq: '오시는 길',
      contact: '문의',
      stats: '예식 정보',
      steps: '일정 안내',
      cta: '참석 여부',
    },
    defaults: withExtras({
      title: '민지 & 준호',
      slogan: '2026년 5월 23일, 우리의 날',
      heroCta: '참석 여부',
      heroCtaSecondary: '오시는 길',
      features: [
        '예식 일정과 타임라인',
        '예식장 안내',
        '모바일 청첩장 공유',
        '참석 여부 응답',
      ],
      testimonials: [
        { name: '가족', role: '축하 메시지', quote: '두 사람의 행복한 시작을 축복합니다.' },
        { name: '친구', role: '축하 메시지', quote: '늘 행복하게 웃는 부부가 되길!' },
        { name: '동료', role: '축하 메시지', quote: '멋진 여정의 시작을 응원합니다.' },
      ],
      pricing: [
        { name: '예식', price: '11:30', desc: '본식', perks: ['1층 그랜드홀', '좌석 안내'] },
        { name: '피로연', price: '12:30', desc: '식사', perks: ['2층 연회장', '뷔페'] },
        { name: '2부', price: '14:00', desc: '소규모 모임', perks: ['가까운 지인', '예약석'] },
      ],
      faq: [
        { q: '주차는 가능한가요?', a: '예식장 주차장을 이용하실 수 있습니다.' },
        { q: '화환 배송 시간은?', a: '예식 시작 2시간 전 도착을 권장합니다.' },
        { q: '복장은 어떻게 준비하나요?', a: '편안한 복장으로 오셔도 됩니다.' },
      ],
      galleryEmojis: ['💍', '🌸', '📸', '💐', '🥂', '✨'],
      stats: [
        { label: '예식장', value: '그랜드홀', desc: '서울 강남' },
        { label: '식사', value: '뷔페', desc: '2층 연회장' },
        { label: '드레스 코드', value: '자유', desc: '편안하게 참석' },
      ],
      steps: [
        { title: '예식 일정', desc: '11:30 본식 시작' },
        { title: '피로연', desc: '12:30 연회장' },
        { title: '2부', desc: '14:00 소규모 모임' },
      ],
      cta: {
        title: '참석 여부를 알려주세요',
        desc: '소중한 발걸음에 감사드립니다.',
        primary: '참석 여부',
        secondary: '오시는 길',
      },
    }),
  },
  photo: {
    id: 'photo',
    label: '사진',
    keywords: ['사진', '포토', '스튜디오', '촬영', '필름'],
    sections: {
      features: '촬영 서비스',
      gallery: '포트폴리오',
      testimonials: '후기',
      pricing: '패키지',
      faq: '안내',
      contact: '예약',
      stats: '스튜디오 지표',
      steps: '촬영 흐름',
      cta: '예약 문의',
    },
    defaults: withExtras({
      title: '렌즈노트 스튜디오',
      slogan: '자연스러운 순간을 기록합니다',
      heroCta: '예약 문의',
      heroCtaSecondary: '포트폴리오',
      features: [
        '인물/브랜딩 촬영',
        '프로필·제품 사진',
        '보정 및 리터칭',
        '스튜디오 대여',
      ],
      testimonials: [
        { name: '규리', role: '촬영 고객', quote: '디렉팅이 세심해서 결과물이 마음에 들어요.' },
        { name: '하준', role: '브랜드 대표', quote: '제품 사진 퀄리티가 훌륭합니다.' },
        { name: '정민', role: '프리랜서', quote: '프로필 사진이 정말 자연스러웠어요.' },
      ],
      pricing: [
        { name: '베이직', price: '₩150,000', desc: '30분 촬영', perks: ['기본 보정', '온라인 전달'] },
        { name: '시그니처', price: '₩320,000', desc: '1시간 촬영', perks: ['고급 보정', '의상 2벌'] },
        { name: '브랜드', price: '₩590,000', desc: '제품+공간', perks: ['상세 컷', '라이프 컷'] },
      ],
      faq: [
        { q: '촬영 소요 시간은?', a: '패키지에 따라 30~90분입니다.' },
        { q: '원본 제공이 가능한가요?', a: '요청 시 원본도 제공합니다.' },
        { q: '야외 촬영도 되나요?', a: '네, 일정 협의 후 가능합니다.' },
      ],
      galleryEmojis: ['📷', '🎞️', '🖼️', '✨', '📸', '🌿'],
      stats: [
        { label: '촬영 건수', value: '1,800+', desc: '누적 촬영' },
        { label: '재방문', value: '64%', desc: '재예약 고객' },
        { label: '보정 시간', value: '48h', desc: '평균 전달 시간' },
      ],
      steps: [
        { title: '예약 상담', desc: '일정과 컨셉 협의' },
        { title: '촬영 진행', desc: '디렉팅과 촬영' },
        { title: '보정 전달', desc: '온라인 전달' },
      ],
      cta: {
        title: '촬영 예약은 지금 바로',
        desc: '원하는 컨셉을 알려 주세요.',
        primary: '예약 상담',
        secondary: '포트폴리오',
      },
    }),
  },
  travel: {
    id: 'travel',
    label: '여행',
    keywords: ['여행', '투어', '일정', '가이드', '항공'],
    sections: {
      features: '추천 포인트',
      gallery: '여행지',
      testimonials: '후기',
      pricing: '패키지',
      faq: '안내',
      contact: '상담',
      stats: '여행 지표',
      steps: '여행 흐름',
      cta: '상담 신청',
    },
    defaults: withExtras({
      title: '폴라 트립',
      slogan: '맞춤 일정으로 떠나는 여행',
      heroCta: '여행 상담',
      heroCtaSecondary: '추천 코스',
      features: [
        '맞춤 일정 설계',
        '현지 가이드 동행',
        '안전 보험 포함',
        '24시간 긴급 지원',
      ],
      testimonials: [
        { name: '지후', role: '여행객', quote: '일정이 알차고 가이드가 친절했어요.' },
        { name: '서진', role: '여행객', quote: '맞춤형이라 만족도가 높았습니다.' },
        { name: '연우', role: '여행객', quote: '문의 응대가 빠르고 꼼꼼해요.' },
      ],
      pricing: [
        { name: '주말 힐링', price: '₩390,000', desc: '2박 3일', perks: ['숙소 포함', '자유 일정'] },
        { name: '시티 투어', price: '₩690,000', desc: '4박 5일', perks: ['가이드 포함', '교통 지원'] },
        { name: '프리미엄', price: '₩1,250,000', desc: '7박 8일', perks: ['맞춤 코스', 'VIP 지원'] },
      ],
      faq: [
        { q: '항공권도 포함인가요?', a: '패키지에 따라 포함 여부가 다릅니다.' },
        { q: '여권이 필요하나요?', a: '해외 일정은 여권이 필요합니다.' },
        { q: '취소 규정은 어떻게 되나요?', a: '출발 7일 전까지 무료 취소 가능합니다.' },
      ],
      galleryEmojis: ['✈️', '🏝️', '🧳', '🗺️', '🌅', '🏔️'],
      stats: [
        { label: '맞춤 일정', value: '240+', desc: '누적 플랜' },
        { label: '가이드', value: '35명', desc: '전문 가이드' },
        { label: '만족도', value: '4.8/5', desc: '여행객 평가' },
      ],
      steps: [
        { title: '상담 접수', desc: '여행 목적 공유' },
        { title: '일정 확정', desc: '맞춤 코스 설계' },
        { title: '출발', desc: '안전하게 여행' },
      ],
      cta: {
        title: '맞춤 여행을 시작하세요',
        desc: '여행 목적과 취향을 알려주세요.',
        primary: '여행 상담',
        secondary: '추천 코스',
      },
    }),
  },
  edu: {
    id: 'edu',
    label: '교육',
    keywords: ['교육', '강의', '수업', '학원', '커리큘럼', '강사'],
    sections: {
      features: '커리큘럼',
      gallery: '수업 스냅',
      testimonials: '수강 후기',
      pricing: '수강권',
      faq: '안내',
      contact: '수강 문의',
      stats: '학습 지표',
      steps: '수강 흐름',
      cta: '무료 체험',
    },
    defaults: withExtras({
      title: '바이브 러닝',
      slogan: '배움이 재미있어지는 온라인 클래스',
      heroCta: '무료 체험',
      heroCtaSecondary: '커리큘럼',
      features: [
        '짧고 집중된 강의',
        '실습 과제 제공',
        '멘토 피드백',
        '커뮤니티 운영',
      ],
      testimonials: [
        { name: '지민', role: '수강생', quote: '짧은 시간에 핵심을 배웠어요.' },
        { name: '서호', role: '수강생', quote: '실습 과제가 도움이 많이 됐습니다.' },
        { name: '은비', role: '수강생', quote: '멘토 피드백이 빠르고 친절했어요.' },
      ],
      pricing: [
        { name: '월 구독', price: '₩29,000', desc: '전체 강의 접근', perks: ['신규 강의', '자료 제공'] },
        { name: '연간', price: '₩290,000', desc: '12개월 이용', perks: ['2개월 무료', '우선 등록'] },
        { name: '기업 교육', price: '문의', desc: '맞춤형 과정', perks: ['전담 매니저', '리포트 제공'] },
      ],
      faq: [
        { q: '수강 기간 제한이 있나요?', a: '구독 기간 동안 무제한입니다.' },
        { q: '수료증 발급이 되나요?', a: '완료 시 발급 가능합니다.' },
        { q: '교재가 필요한가요?', a: '별도 교재 없이 진행합니다.' },
      ],
      galleryEmojis: ['📚', '🧑‍🏫', '📝', '💻', '🎓', '✨'],
      stats: [
        { label: '수강생', value: '7,800+', desc: '누적 수강생' },
        { label: '완강률', value: '78%', desc: '3개월 기준' },
        { label: '강의 수', value: '180+', desc: '최신 강의' },
      ],
      steps: [
        { title: '수강 신청', desc: '원하는 과정 선택' },
        { title: '학습 진행', desc: '강의와 과제 수행' },
        { title: '피드백', desc: '멘토 피드백 제공' },
      ],
      cta: {
        title: '지금 무료 체험을 시작하세요',
        desc: '첫 주차 강의를 무료로 제공합니다.',
        primary: '무료 체험',
        secondary: '커리큘럼 보기',
      },
    }),
  },
  tech: {
    id: 'tech',
    label: '테크',
    keywords: ['테크', 'IT', '개발', '솔루션', 'SaaS', 'API'],
    sections: {
      features: '핵심 기능',
      gallery: '제품',
      testimonials: '사용 후기',
      pricing: '플랜',
      faq: '기술 문의',
      contact: '상담',
      stats: '지표',
      steps: '도입 흐름',
      cta: '지금 시작',
    },
    defaults: withExtras({
      title: '스파크 테크',
      slogan: '빠르게 구축하는 제품 개발 팀',
      heroCta: '상담 요청',
      heroCtaSecondary: '기술 스택',
      features: [
        'MVP 빠른 출시',
        'API 통합과 자동화',
        '클라우드 인프라 운영',
        '보안·성능 최적화',
      ],
      testimonials: [
        { name: '프로젝트 A', role: 'CTO', quote: '개발 속도가 크게 향상되었습니다.' },
        { name: '서비스 B', role: 'PO', quote: '요구사항 반영이 빠르고 정확해요.' },
        { name: '기업 C', role: 'IT팀', quote: '안정성과 유지보수가 뛰어납니다.' },
      ],
      pricing: [
        { name: 'Sprint', price: '₩1,900,000', desc: '2주 집중 개발', perks: ['핵심 기능', '리포트 제공'] },
        { name: 'Growth', price: '₩5,200,000', desc: '6주 개발', perks: ['확장 기능', 'QA 지원'] },
        { name: 'Enterprise', price: '문의', desc: '맞춤형', perks: ['전담 팀', 'SLA'] },
      ],
      faq: [
        { q: '개발 범위는 어떻게 정하나요?', a: '워크숍을 통해 범위를 설정합니다.' },
        { q: '유지보수도 제공하나요?', a: '필요 시 별도 계약으로 제공합니다.' },
        { q: '보안 기준은 어떻게 되나요?', a: '표준 보안 가이드를 따릅니다.' },
      ],
      galleryEmojis: ['⚡', '🧱', '🔗', '🧪', '☁️', '🛰️'],
      stats: [
        { label: 'SaaS 런칭', value: '45+', desc: '누적 런칭' },
        { label: '평균 개선', value: '32%', desc: '성능 최적화' },
        { label: '자동화', value: '120+', desc: '워크플로우' },
      ],
      steps: [
        { title: '요구 분석', desc: '목표와 KPI 정의' },
        { title: '프로토타입', desc: '빠른 검증' },
        { title: '확장', desc: '스케일링 지원' },
      ],
      cta: {
        title: '제품 개발을 함께 시작해요',
        desc: '기술 상담을 통해 최적의 스택을 추천합니다.',
        primary: '상담 신청',
        secondary: '기술 자료',
      },
    }),
  },
}

export const TEMPLATE_ORDER = [
  'cafe',
  'portfolio',
  'shop',
  'blog',
  'company',
  'restaurant',
  'fitness',
  'wedding',
  'photo',
  'travel',
  'edu',
  'tech',
]

export const TEMPLATE_LIST = TEMPLATE_ORDER.map((id) => TEMPLATE_PRESETS[id])

export function getTemplateDefaults(templateId) {
  const preset = TEMPLATE_PRESETS[templateId] || TEMPLATE_PRESETS.cafe
  return {
    title: preset.defaults.title,
    slogan: preset.defaults.slogan,
    heroCta: preset.defaults.heroCta,
    heroCtaSecondary: preset.defaults.heroCtaSecondary,
    features: preset.defaults.features,
    testimonials: preset.defaults.testimonials,
    pricing: preset.defaults.pricing,
    faq: preset.defaults.faq,
    stats: preset.defaults.stats,
    steps: preset.defaults.steps,
    cta: preset.defaults.cta,
    contact: preset.defaults.contact,
    socials: preset.defaults.socials,
  }
}
